//This variable is used to point the client-side code to the Google App Script server that handles data requests. Every time the code in Google App Script is modified, the server must be deployed again. When that happens the code returned by the function must be updated.
const gas_deployment_id='AKfycbzW53_vqdCwKRy4ImHVdX5fAop9SfLErJjTuO2XKD9b9KSIf_eFkK6pOdL-w21JAV-EaA'

//Static Airtable IDs to link to pages generated by airtable in the app
const request_time_off_share = 'shrR7yun3axGBHfYD'
const show_time_off_share = 'shrCIdSD4TvKwPb0T'
const show_locations_share = 'shrqv5K093j0Tr1J4'
